[2024-06-07T14:11:04.038+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-07T14:11:04.063+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_postgres.download_and_insert_data scheduled__2024-06-05T00:00:00+00:00 [queued]>
[2024-06-07T14:11:04.074+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_postgres.download_and_insert_data scheduled__2024-06-05T00:00:00+00:00 [queued]>
[2024-06-07T14:11:04.075+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2024-06-07T14:11:04.091+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_and_insert_data> on 2024-06-05 00:00:00+00:00
[2024-06-07T14:11:04.099+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=218) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-07T14:11:04.101+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 's3_postgres', 'download_and_insert_data', 'scheduled__2024-06-05T00:00:00+00:00', '--job-id', '839', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpvq105x1v']
[2024-06-07T14:11:04.102+0000] {standard_task_runner.py:63} INFO - Started process 220 to run task
[2024-06-07T14:11:04.103+0000] {standard_task_runner.py:91} INFO - Job 839: Subtask download_and_insert_data
[2024-06-07T14:11:04.166+0000] {task_command.py:426} INFO - Running <TaskInstance: s3_postgres.download_and_insert_data scheduled__2024-06-05T00:00:00+00:00 [running]> on host 1dcaa0c0151e
[2024-06-07T14:11:04.273+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_postgres' AIRFLOW_CTX_TASK_ID='download_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-05T00:00:00+00:00'
[2024-06-07T14:11:04.275+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-07T14:11:07.808+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-06-07T14:11:11.239+0000] {logging_mixin.py:188} INFO - Data insertion complete
[2024-06-07T14:11:11.242+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-07T14:11:11.243+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-07T14:11:11.257+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=s3_postgres, task_id=download_and_insert_data, run_id=scheduled__2024-06-05T00:00:00+00:00, execution_date=20240605T000000, start_date=20240607T141104, end_date=20240607T141111
[2024-06-07T14:11:11.317+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-07T14:11:11.372+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-07T14:11:11.377+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
