[2024-06-05T16:42:30.070+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T16:42:30.097+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_postgres.create_postgres_table scheduled__2024-06-04T00:00:00+00:00 [queued]>
[2024-06-05T16:42:30.107+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_postgres.create_postgres_table scheduled__2024-06-04T00:00:00+00:00 [queued]>
[2024-06-05T16:42:30.108+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 4
[2024-06-05T16:42:30.126+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): create_postgres_table> on 2024-06-04 00:00:00+00:00
[2024-06-05T16:42:30.133+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=172) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-05T16:42:30.135+0000] {standard_task_runner.py:63} INFO - Started process 176 to run task
[2024-06-05T16:42:30.136+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 's3_postgres', 'create_postgres_table', 'scheduled__2024-06-04T00:00:00+00:00', '--job-id', '711', '--raw', '--subdir', 'DAGS_FOLDER/pipe.py', '--cfg-path', '/tmp/tmpkqzs8iuk']
[2024-06-05T16:42:30.138+0000] {standard_task_runner.py:91} INFO - Job 711: Subtask create_postgres_table
[2024-06-05T16:42:30.199+0000] {task_command.py:426} INFO - Running <TaskInstance: s3_postgres.create_postgres_table scheduled__2024-06-04T00:00:00+00:00 [running]> on host 3ca4815e3382
[2024-06-05T16:42:30.455+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_postgres' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2024-06-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-04T00:00:00+00:00'
[2024-06-05T16:42:30.462+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T16:42:30.478+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-06-05T16:42:30.521+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T16:42:30.523+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipe.py", line 84, in create_table_postgres
    postgres_hook.run(create_table_query)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 411, in run
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 161, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "host.docker.internal" (192.168.65.254), port 5432 failed: FATAL:  password authentication failed for user "***"

[2024-06-05T16:42:30.565+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=s3_postgres, task_id=create_postgres_table, run_id=scheduled__2024-06-04T00:00:00+00:00, execution_date=20240604T000000, start_date=20240605T164230, end_date=20240605T164230
[2024-06-05T16:42:30.588+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 711 for task create_postgres_table (connection to server at "host.docker.internal" (192.168.65.254), port 5432 failed: FATAL:  password authentication failed for user "***"
; 176)
[2024-06-05T16:42:30.631+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-05T16:42:30.671+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-05T16:42:30.674+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-05T17:47:14.156+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T17:47:14.179+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_postgres.create_postgres_table scheduled__2024-06-04T00:00:00+00:00 [queued]>
[2024-06-05T17:47:14.186+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_postgres.create_postgres_table scheduled__2024-06-04T00:00:00+00:00 [queued]>
[2024-06-05T17:47:14.187+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 4
[2024-06-05T17:47:14.201+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): create_postgres_table> on 2024-06-04 00:00:00+00:00
[2024-06-05T17:47:14.209+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=125) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-05T17:47:14.211+0000] {standard_task_runner.py:63} INFO - Started process 127 to run task
[2024-06-05T17:47:14.211+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 's3_postgres', 'create_postgres_table', 'scheduled__2024-06-04T00:00:00+00:00', '--job-id', '804', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpkn1bwe8i']
[2024-06-05T17:47:14.213+0000] {standard_task_runner.py:91} INFO - Job 804: Subtask create_postgres_table
[2024-06-05T17:47:14.272+0000] {task_command.py:426} INFO - Running <TaskInstance: s3_postgres.create_postgres_table scheduled__2024-06-04T00:00:00+00:00 [running]> on host b9a8b9be1324
[2024-06-05T17:47:14.368+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_postgres' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2024-06-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-04T00:00:00+00:00'
[2024-06-05T17:47:14.370+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T17:47:14.379+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-06-05T17:47:14.392+0000] {sql.py:470} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS potential_customers (
        UserID TEXT,
        basket_icon_click INTEGER,
        basket_add_list INTEGER,
        basket_add_detail INTEGER,
        sort_by INTEGER,
        image_picker INTEGER,
        account_page_click INTEGER,
        promo_banner_click INTEGER,
        detail_wishlist_add INTEGER,
        list_size_dropdown INTEGER,
        closed_minibasket_click INTEGER,
        checked_delivery_detail INTEGER,
        checked_returns_detail INTEGER,
        sign_in INTEGER,
        saw_checkout INTEGER,
        saw_sizecharts INTEGER,
        saw_delivery INTEGER,
        saw_account_upgrade INTEGER,
        saw_homepage INTEGER,
        device_mobile INTEGER,
        device_computer INTEGER,
        device_tablet INTEGER,
        returning_user INTEGER,
        loc_uk INTEGER,
        ordered INTEGER,
        created_at TIMESTAMP
    );
    , parameters: None
[2024-06-05T17:47:14.416+0000] {logging_mixin.py:188} INFO - Create table successful
[2024-06-05T17:47:14.417+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-05T17:47:14.417+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T17:47:14.427+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=s3_postgres, task_id=create_postgres_table, run_id=scheduled__2024-06-04T00:00:00+00:00, execution_date=20240604T000000, start_date=20240605T174714, end_date=20240605T174714
[2024-06-05T17:47:14.466+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-05T17:47:14.491+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-05T17:47:14.493+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
