[2024-06-05T16:36:18.405+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T16:36:18.431+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_postgres.create_postgres_table scheduled__2024-06-04T00:00:00+00:00 [queued]>
[2024-06-05T16:36:18.441+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_postgres.create_postgres_table scheduled__2024-06-04T00:00:00+00:00 [queued]>
[2024-06-05T16:36:18.442+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-05T16:36:18.459+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): create_postgres_table> on 2024-06-04 00:00:00+00:00
[2024-06-05T16:36:18.470+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=81) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-05T16:36:18.473+0000] {standard_task_runner.py:63} INFO - Started process 86 to run task
[2024-06-05T16:36:18.473+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 's3_postgres', 'create_postgres_table', 'scheduled__2024-06-04T00:00:00+00:00', '--job-id', '706', '--raw', '--subdir', 'DAGS_FOLDER/pipe.py', '--cfg-path', '/tmp/tmps3kyaie6']
[2024-06-05T16:36:18.475+0000] {standard_task_runner.py:91} INFO - Job 706: Subtask create_postgres_table
[2024-06-05T16:36:18.546+0000] {task_command.py:426} INFO - Running <TaskInstance: s3_postgres.create_postgres_table scheduled__2024-06-04T00:00:00+00:00 [running]> on host 3ca4815e3382
[2024-06-05T16:36:18.653+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_postgres' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2024-06-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-04T00:00:00+00:00'
[2024-06-05T16:36:18.655+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T16:36:18.668+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-06-05T16:36:18.675+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T16:36:18.676+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipe.py", line 84, in create_table_postgres
    postgres_hook.run(create_table_query)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 411, in run
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 161, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "host.docker.local" to address: Name or service not known

[2024-06-05T16:36:18.692+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=s3_postgres, task_id=create_postgres_table, run_id=scheduled__2024-06-04T00:00:00+00:00, execution_date=20240604T000000, start_date=20240605T163618, end_date=20240605T163618
[2024-06-05T16:36:18.709+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 706 for task create_postgres_table (could not translate host name "host.docker.local" to address: Name or service not known
; 86)
[2024-06-05T16:36:18.729+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-05T16:36:18.741+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-05T17:17:02.085+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T17:17:02.137+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_postgres.create_postgres_table scheduled__2024-06-04T00:00:00+00:00 [queued]>
[2024-06-05T17:17:02.158+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_postgres.create_postgres_table scheduled__2024-06-04T00:00:00+00:00 [queued]>
[2024-06-05T17:17:02.159+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-05T17:17:02.211+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): create_postgres_table> on 2024-06-04 00:00:00+00:00
[2024-06-05T17:17:02.226+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=89) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-05T17:17:02.227+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 's3_postgres', 'create_postgres_table', 'scheduled__2024-06-04T00:00:00+00:00', '--job-id', '739', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp7if6fl_2']
[2024-06-05T17:17:02.230+0000] {standard_task_runner.py:63} INFO - Started process 100 to run task
[2024-06-05T17:17:02.232+0000] {standard_task_runner.py:91} INFO - Job 739: Subtask create_postgres_table
[2024-06-05T17:17:02.350+0000] {task_command.py:426} INFO - Running <TaskInstance: s3_postgres.create_postgres_table scheduled__2024-06-04T00:00:00+00:00 [running]> on host 68d2d1c90970
[2024-06-05T17:17:02.488+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_postgres' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2024-06-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-04T00:00:00+00:00'
[2024-06-05T17:17:02.490+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T17:17:02.503+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-06-05T17:17:02.524+0000] {sql.py:470} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS potential_customers (
        UserID TEXT,
        basket_icon_click INTEGER,
        basket_add_list INTEGER,
        basket_add_detail INTEGER,
        sort_by INTEGER,
        image_picker INTEGER,
        account_page_click INTEGER,
        promo_banner_click INTEGER,
        detail_wishlist_add INTEGER,
        list_size_dropdown INTEGER,
        closed_minibasket_click INTEGER,
        checked_delivery_detail INTEGER,
        checked_returns_detail INTEGER,
        sign_in INTEGER,
        saw_checkout INTEGER,
        saw_sizecharts INTEGER,
        saw_delivery INTEGER,
        saw_account_upgrade INTEGER,
        saw_homepage INTEGER,
        device_mobile INTEGER,
        device_computer INTEGER,
        device_tablet INTEGER,
        returning_user INTEGER,
        loc_uk INTEGER,
        ordered INTEGER,
        created_at TIMESTAMP
    );
    , parameters: None
[2024-06-05T17:17:02.533+0000] {logging_mixin.py:188} INFO - Create table successful
[2024-06-05T17:17:02.535+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-05T17:17:02.535+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T17:17:02.551+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=s3_postgres, task_id=create_postgres_table, run_id=scheduled__2024-06-04T00:00:00+00:00, execution_date=20240604T000000, start_date=20240605T171702, end_date=20240605T171702
[2024-06-05T17:17:02.610+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-05T17:17:02.657+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-05T17:17:02.660+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
