[2024-06-05T16:50:51.654+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T16:50:51.688+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_postgres.fetch_recent_data scheduled__2024-06-04T00:00:00+00:00 [queued]>
[2024-06-05T16:50:51.699+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_postgres.fetch_recent_data scheduled__2024-06-04T00:00:00+00:00 [queued]>
[2024-06-05T16:50:51.700+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2024-06-05T16:50:51.718+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_recent_data> on 2024-06-04 00:00:00+00:00
[2024-06-05T16:50:51.730+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=70) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-05T16:50:51.733+0000] {standard_task_runner.py:63} INFO - Started process 74 to run task
[2024-06-05T16:50:51.732+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 's3_postgres', 'fetch_recent_data', 'scheduled__2024-06-04T00:00:00+00:00', '--job-id', '723', '--raw', '--subdir', 'DAGS_FOLDER/pipe.py', '--cfg-path', '/tmp/tmp275vy_m2']
[2024-06-05T16:50:51.734+0000] {standard_task_runner.py:91} INFO - Job 723: Subtask fetch_recent_data
[2024-06-05T16:50:51.805+0000] {task_command.py:426} INFO - Running <TaskInstance: s3_postgres.fetch_recent_data scheduled__2024-06-04T00:00:00+00:00 [running]> on host 6dbcf9923072
[2024-06-05T16:50:51.910+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_postgres' AIRFLOW_CTX_TASK_ID='fetch_recent_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-04T00:00:00+00:00'
[2024-06-05T16:50:51.912+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T16:50:51.923+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-06-05T16:50:51.944+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T16:50:51.945+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipe.py", line 124, in fetch_recent_data_to_csv
    df.to_csv(output_file, index=False)
    ^^
NameError: name 'df' is not defined
[2024-06-05T16:50:51.959+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=s3_postgres, task_id=fetch_recent_data, run_id=scheduled__2024-06-04T00:00:00+00:00, execution_date=20240604T000000, start_date=20240605T165051, end_date=20240605T165051
[2024-06-05T16:50:51.974+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 723 for task fetch_recent_data (name 'df' is not defined; 74)
[2024-06-05T16:50:51.988+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-05T16:50:52.012+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-05T16:50:52.015+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-05T17:30:52.455+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T17:30:52.490+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_postgres.fetch_recent_data scheduled__2024-06-04T00:00:00+00:00 [queued]>
[2024-06-05T17:30:52.503+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_postgres.fetch_recent_data scheduled__2024-06-04T00:00:00+00:00 [queued]>
[2024-06-05T17:30:52.504+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2024-06-05T17:30:52.523+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_recent_data> on 2024-06-04 00:00:00+00:00
[2024-06-05T17:30:52.532+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=78) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-05T17:30:52.534+0000] {standard_task_runner.py:63} INFO - Started process 82 to run task
[2024-06-05T17:30:52.535+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 's3_postgres', 'fetch_recent_data', 'scheduled__2024-06-04T00:00:00+00:00', '--job-id', '770', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp7r7poofs']
[2024-06-05T17:30:52.537+0000] {standard_task_runner.py:91} INFO - Job 770: Subtask fetch_recent_data
[2024-06-05T17:30:52.606+0000] {task_command.py:426} INFO - Running <TaskInstance: s3_postgres.fetch_recent_data scheduled__2024-06-04T00:00:00+00:00 [running]> on host 0a6aac87d868
[2024-06-05T17:30:52.713+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_postgres' AIRFLOW_CTX_TASK_ID='fetch_recent_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-04T00:00:00+00:00'
[2024-06-05T17:30:52.715+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T17:30:52.725+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-06-05T17:30:52.763+0000] {logging_mixin.py:188} INFO - Data fetch complete
[2024-06-05T17:30:52.765+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-05T17:30:52.766+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T17:30:52.777+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=s3_postgres, task_id=fetch_recent_data, run_id=scheduled__2024-06-04T00:00:00+00:00, execution_date=20240604T000000, start_date=20240605T173052, end_date=20240605T173052
[2024-06-05T17:30:52.829+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-05T17:30:52.861+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-05T17:30:52.863+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
