[2024-06-05T16:52:48.323+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T16:52:48.347+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_postgres.fetch_recent_data manual__2024-06-05T16:35:59.651756+00:00 [queued]>
[2024-06-05T16:52:48.357+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_postgres.fetch_recent_data manual__2024-06-05T16:35:59.651756+00:00 [queued]>
[2024-06-05T16:52:48.358+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 4
[2024-06-05T16:52:48.373+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_recent_data> on 2024-06-05 16:35:59.651756+00:00
[2024-06-05T16:52:48.380+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=99) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-05T16:52:48.382+0000] {standard_task_runner.py:63} INFO - Started process 101 to run task
[2024-06-05T16:52:48.382+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 's3_postgres', 'fetch_recent_data', 'manual__2024-06-05T16:35:59.651756+00:00', '--job-id', '726', '--raw', '--subdir', 'DAGS_FOLDER/pipe.py', '--cfg-path', '/tmp/tmpsfq_dcb2']
[2024-06-05T16:52:48.383+0000] {standard_task_runner.py:91} INFO - Job 726: Subtask fetch_recent_data
[2024-06-05T16:52:48.432+0000] {task_command.py:426} INFO - Running <TaskInstance: s3_postgres.fetch_recent_data manual__2024-06-05T16:35:59.651756+00:00 [running]> on host 6dbcf9923072
[2024-06-05T16:52:48.530+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_postgres' AIRFLOW_CTX_TASK_ID='fetch_recent_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-05T16:35:59.651756+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-05T16:35:59.651756+00:00'
[2024-06-05T16:52:48.532+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T16:52:48.543+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-06-05T16:52:48.572+0000] {logging_mixin.py:188} INFO - Data fetch complete
[2024-06-05T16:52:48.573+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-05T16:52:48.574+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T16:52:48.584+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=s3_postgres, task_id=fetch_recent_data, run_id=manual__2024-06-05T16:35:59.651756+00:00, execution_date=20240605T163559, start_date=20240605T165248, end_date=20240605T165248
[2024-06-05T16:52:48.637+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-05T16:52:48.655+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-05T16:52:48.658+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
